name: Release QMK Firmware

on:
  push


permissions: write-all

jobs:
  build_vial:
    uses: ./.github/workflows/build-firmware.yml
    with:
      keyboard: ${{ matrix.keyboard }}
      keymap: ${{ matrix.keymap }}
      side: ${{ matrix.side }}

    strategy:
      matrix:
        keyboard: [ svalboard/trackball/pmw3389 ]
        keymap: [ vial ]
        side: [ left ]
